# Generated by Django 3.1.3 on 2021-12-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='answer_correct',
            field=models.BooleanField(default=False),
        ),
    ]
